# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
before_install:
  -sudo apt-get -qq update
  -sudo apt-get install libglm-dev
# Build steps
script:
  - mkdir build
  - make clang
