# Enable C++ support
#language: cpp
# Compiler selection
#compiler:
#  - clang
#  - gcc
#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install libglm-dev
# Build steps
#script:
#  - mkdir build
#  - make travistests

#sudo: false
# Enable C++
#language: cpp
# Which compilers to test agains
#compiler:
#  - gcc
#  - clang
#install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-5 -std=c++14" CC="gcc-5"; fi
#  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7 -std=c++14" CC="clang-3.4"; fi
#addons:
 # apt:
  #  sources:
   # - llvm-toolchain-precise
   # - ubuntu-toolchain-r-test
   # packages:
   # - gcc-5
   # - g++-5
   # - clang-3.7
   # - libglm-dev
#script:
#  - mkdir build
#  - make travistests
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
script:
  -mkdir build
  -make travistests

